In [1]:
import numpy as np

In [6]:
a = np.random.randn(1234,12)
b = np.random.randn(12,13)
a*b

ValueError: operands could not be broadcast together with shapes (1234,12) (12,13) 

In [23]:
a = np.random.randn(3,3)

In [24]:
a

array([[ 0.02517975, -0.57453555, -0.85995076],
       [-0.81312782, -0.70688334, -0.32450386],
       [ 0.15673884, -2.09008017,  1.48050249]])

In [25]:
b = np.random.randn(3,1)

In [26]:
b

array([[ 1.41663355],
       [ 1.08916192],
       [-0.59794221]])

In [27]:
a * b

array([[ 0.03567048, -0.81390634, -1.2182351 ],
       [-0.88562786, -0.76991041, -0.35343724],
       [-0.09372077,  1.24974716, -0.88525493]])

In [21]:
a.T + b

array([[-0.93833708,  2.48476586,  0.13197867],
       [ 0.03094207,  0.77049162, -1.21820942],
       [-0.24188639, -1.27255234, -4.0852055 ],
       [ 0.96186261, -1.73208522,  0.00959592]])

In [22]:
b.T

array([[ 1.2062481 , -0.1279952 , -2.14497907, -0.2340827 ]])